// ── Story mode — act definitions, enemy waves, dialogue ──────────────────────

const STORY_WORLD_W = 2400;

// Per-act enemy definitions
const STORY_ENEMY_DEFS = {
  // Act 2 — Ancients
  golem:      { speed: 0.55, hp: 3, w: 34, h: 58, throwInterval: 3500, throwSpeed: 1.0, color: '#8B7355', pants: '#6B5335' },
  hex_spirit: { speed: 1.3,  hp: 1, w: 18, h: 40, throwInterval: 1500, throwSpeed: 5.5, color: '#9955CC', pants: '#7733AA', teleports: true },
  // Act 3 — Military
  soldier:    { speed: 1.5,  hp: 1, w: 20, h: 44, throwInterval: 1800, throwSpeed: 6.5, color: '#556677', pants: '#334455' },
  drone:      { speed: 1.2,  hp: 1, w: 24, h: 28, throwInterval: 1600, throwSpeed: 5.5, color: '#445566', pants: '#334455', floats: true },
  // Act 4 — Medieval
  knight:     { speed: 0.9,  hp: 3, w: 24, h: 50, throwInterval: 2800, throwSpeed: 5.0, color: '#778899', pants: '#445566' },
  archer:     { speed: 0.7,  hp: 1, w: 18, h: 44, throwInterval: 1100, throwSpeed: 8.0, color: '#8B6914', pants: '#5A4010' },
  // Act 5 — Tech
  robot:      { speed: 1.8,  hp: 2, w: 22, h: 48, throwInterval: 1500, throwSpeed: 7.5, color: '#5599AA', pants: '#336677' },
  hack_drone: { speed: 1.4,  hp: 1, w: 28, h: 28, throwInterval: 2000, throwSpeed: 6.0, color: '#00CCAA', pants: '#009988', floats: true },
  // Act 5 NEW — Digital Horrors
  tendril:      { speed: 0.45, hp: 2, w: 20, h: 52, throwInterval: 1100, throwSpeed: 6.5, color: '#33CC66', pants: '#116633' },
  glitch:       { speed: 2.8,  hp: 1, w: 18, h: 38, throwInterval: 750,  throwSpeed: 9.0, color: '#FF00AA', pants: '#CC0077' },
  pulse_orb:    { speed: 1.0,  hp: 1, w: 24, h: 24, throwInterval: 1200, throwSpeed: 8.0, color: '#00DDFF', pants: '#0099BB', floats: true },
  overload_bot: { speed: 0.7,  hp: 3, w: 28, h: 54, throwInterval: 2000, throwSpeed: 5.5, color: '#FF5500', pants: '#CC3300' },

  // ── BOSSES ────────────────────────────────────────────────────────────────
  patient_zero:   { speed: 0.6,  hp: 16, w: 56, h: 88, throwInterval: 700,  throwSpeed: 5.5, color: '#5a3a2a', pants: '#3a2a1a', isBoss: true },
  stone_guardian: { speed: 0.4,  hp: 18, w: 68, h: 100, throwInterval: 3000, throwSpeed: 4.0, color: '#7a6a4a', pants: '#5a4a2a', isBoss: true },
  mech_fluffkins: { speed: 1.0,  hp: 20, w: 62, h: 90,  throwInterval: 2500, throwSpeed: 6.0, color: '#445566', pants: '#223344', isBoss: true, floats: true },
  iron_champion:  { speed: 1.2,  hp: 20, w: 58, h: 96,  throwInterval: 3500, throwSpeed: 5.0, color: '#667788', pants: '#445566', isBoss: true },
  nexus_core:     { speed: 0.5,  hp: 24, w: 72, h: 80,  throwInterval: 1800, throwSpeed: 7.0, color: '#003355', pants: '#001133', isBoss: true, floats: true },
};

const STORY_ACTS = [
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'city',
    title: 'ACT 1',
    zone: 'CITY RUINS',
    enemyCategory: 'INFECTED',
    synopsis: 'A plague has turned the city. Dr. Wendy has the cure — but first, clear the streets and take down Patient Zero.',
    bg: { sky: '#1a1a2e', mid: '#2a2a3e', ground: '#3a2a1a', accent: '#FF6600' },
    waves: [
      [{ type: 'zombie',      count: 1 }],
      [{ type: 'zombie',      count: 2 }],
      [{ type: 'zombie',      count: 3 }],
      [{ type: 'zombie',      count: 4 }],
      [{ type: 'zombie',      count: 3 }, { type: 'fast_zombie', count: 1 }],
      [{ type: 'fast_zombie', count: 2 }],
      [{ type: 'fast_zombie', count: 3 }],
      [{ type: 'zombie',      count: 2 }, { type: 'fast_zombie', count: 2 }],
      [{ type: 'zombie',      count: 3 }, { type: 'fast_zombie', count: 3 }],
      // Wave 10: BOSS — Patient Zero (HEAD ONLY)
      [{ type: 'patient_zero', count: 1 }],
    ],
    npc: {
      name: 'DR. WENDY',
      col: '#88FF88',
      portrait: 'wendy',
      introLines: [
        "Oh THANK GOODNESS. Living humans! Real ones!",
        "I'm Dr. Wendy. Epidemiologist. Dodgeball enthusiast. Currently crying a little.",
        "I've been trapped in these ruins for three weeks studying the plague.",
        "Good news: I know what cures it. Bad news: it's extremely embarrassing.",
        "The cure is kinetic impact to the cranium. Specifically from a dodgeball.",
        "I published this in a peer-reviewed journal. Nobody read it.",
        "There's something big ahead. BIG big. Wearing a barbed wire crown kind of big.",
        "Patient Zero — the original infected. Take it down and this area goes quiet.",
        "Hit it in the HEAD. The infection concentrates there. Body shots bounce right off.",
        "I'll be hiding behind this wall. For safety. And definitely not because I'm scared.",
      ],
      outroLines: [
        "You... you actually did it.",
        "Patient Zero is down. The horde is retreating!",
        "I'm going to have to rewrite my paper to mention 'brave idiots with dodgeballs'.",
        "The infection is spreading east. Jungle temple, ancient ruins zone.",
        "My colleague Prof. Biff went there to research. He's been gone for weeks.",
        "Knowing Biff, he's either found the answer or been adopted by the golems.",
        "Either way — go. You're clearly the only people doing anything about this.",
        "I'll start synthesising data here. Maybe write a follow-up paper.",
        "'Dodgeball As Pandemic Treatment: A Case Study'. I'll cite you both.",
        "Thank you. Genuinely. Now GO. More zombies incoming from the east.",
      ],
    },
    mapPos: { x: 130, y: 355 },
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'jungle',
    title: 'ACT 2',
    zone: 'JUNGLE TEMPLE',
    enemyCategory: 'ANCIENTS',
    synopsis: 'Prof. Biff found a prophecy pointing east. Ancient stone golems guard the jungle temple — and its secrets.',
    bg: { sky: '#0a1a0a', mid: '#1a3a1a', ground: '#2a4a1a', accent: '#44FF88' },
    waves: [
      [{ type: 'golem',      count: 1 }],
      [{ type: 'golem',      count: 2 }],
      [{ type: 'golem',      count: 3 }],
      [{ type: 'golem',      count: 4 }],
      [{ type: 'golem',      count: 3 }, { type: 'hex_spirit', count: 1 }],
      [{ type: 'hex_spirit', count: 1 }],
      [{ type: 'hex_spirit', count: 2 }],
      [{ type: 'golem',      count: 2 }, { type: 'hex_spirit', count: 1 }],
      [{ type: 'golem',      count: 3 }, { type: 'hex_spirit', count: 1 }],
      // Wave 10: BOSS — Stone Guardian (DUAL HIT within 400ms)
      [{ type: 'stone_guardian', count: 1 }],
    ],
    npc: {
      name: 'PROF. BIFF',
      col: '#DDAA44',
      portrait: 'biff',
      introLines: [
        "You FOUND ME! How did you know I was behind this specific rock?",
        "I am Professor Biff. Archaeologist. Mostly fine. Minor rock-related PTSD.",
        "I came here to find the Tome of Dodgeball Prophecy — and I FOUND it!",
        "The prophecy is clear: 'The cure lies with those who throw true.'",
        "Which I initially interpreted as a metaphor. Then I watched you fight zombies.",
        "Oh. Oh it's literal. It's always been literal.",
        "There's a guardian ahead. Ancient. Stone. Possibly cursed, definitely angry.",
        "The Stone Guardian absorbed my entire team's equipment. In one stomp.",
        "You can't hit it straight on — it absorbs the impact. You must DOUBLE UP.",
        "Two hits in rapid succession, like a one-two punch. Overwhelm its absorption!",
      ],
      outroLines: [
        "EXTRAORDINARY! The Stone Guardian has been defeated!",
        "The temple runes are going dark. The ancient seal is broken!",
        "I found the next clue in the Tome. Section 7, footnote 43, subsection C.",
        "'Seek the cold where the general commands the sky.' Snow Base, obviously.",
        "General Fluffkins. I've heard of them. The cat is... a mystery.",
        "My sources say Fluffkins had access to a research vial. CRUCIAL data inside.",
        "The general is unconventional. Don't let the meowing mislead you.",
        "Also the Snow Base has a giant mechanical cat suit. Which Fluffkins built. Alone.",
        "I'm staying here to catalogue these ruins. Someone has to do the science.",
        "You're doing an incredible job. The Tome says you will succeed. Probably.",
      ],
    },
    mapPos: { x: 238, y: 290 },
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'snow',
    title: 'ACT 3',
    zone: 'SNOW BASE',
    enemyCategory: 'MILITARY',
    synopsis: 'A military base in the frozen north, commanded by a cat. Gen. Fluffkins holds critical research — and a rogue mech suit.',
    bg: { sky: '#1a2a3a', mid: '#2a3a4a', ground: '#c8d8e8', accent: '#88CCFF' },
    waves: [
      [{ type: 'soldier', count: 1 }],
      [{ type: 'soldier', count: 2 }],
      [{ type: 'soldier', count: 3 }],
      [{ type: 'soldier', count: 4 }],
      [{ type: 'soldier', count: 4 }, { type: 'drone', count: 1 }],
      [{ type: 'drone',   count: 2 }],
      [{ type: 'drone',   count: 3 }],
      [{ type: 'soldier', count: 3 }, { type: 'drone', count: 2 }],
      [{ type: 'soldier', count: 4 }, { type: 'drone', count: 3 }],
      // Wave 10: BOSS — Mech Fluffkins (PHASE WINDOW — blue shield cycles)
      [{ type: 'mech_fluffkins', count: 1 }],
    ],
    npc: {
      name: 'GEN. FLUFFKINS',
      col: '#AAAAFF',
      portrait: 'fluffkins',
      introLines: [
        "*MEOW*",
        "I am General Fluffkins. Former lab cat. Current base commander. Deeply misunderstood.",
        "Before you say anything — YES I took the vial. It smelled like mango sports drink.",
        "IT WAS MANGO SPORTS DRINK. I drank it. I have no regrets. Zero percent regrets.",
        "But I found something while defending this base from the infected soldiers.",
        "The REAL research. The actual cure data. I have it right here.",
        "My mechs and drones have been compromised. I can't stop them alone.",
        "And my Mech Fluffkins suit has... acquired sentience. That's concerning.",
        "It activates a blue shield periodically. Blue glow means INVULNERABLE — wait it out.",
        "Hit it during the vulnerable window. Quickly. It learns from dodging.",
      ],
      outroLines: [
        "*quiet meow*",
        "My suit is defeated. I feel... relieved? That's surprising.",
        "I loved that thing. I built it from scratch. But it stopped listening to me.",
        "Here. The research data. The cure IS kinetic impact, just like Dr. Wendy theorized.",
        "But for a PLANETARY broadcast you need the Royal Castle signal array.",
        "The Princesses know this. They've KNOWN for months. I may have been brief with them.",
        "I sent them a strongly-worded memo. With claw marks on it. They ignored me.",
        "You'll have to get past the castle guard first. Knights. Archers. Very dramatic.",
        "Tell the Princesses General Fluffkins sends regards. And a formal apology. Maybe.",
        "Go. The castle is south-east. And — good luck. From me. Sincerely. *meow*",
      ],
    },
    mapPos: { x: 352, y: 215 },
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'castle',
    title: 'ACT 4',
    zone: 'ROYAL CASTLE',
    enemyCategory: 'MEDIEVAL',
    bg: { sky: '#1a1208', mid: '#2a2010', ground: '#3a2a10', accent: '#FFD700' },
    waves: [
      [{ type: 'knight', count: 1 }],
      [{ type: 'knight', count: 2 }],
      [{ type: 'knight', count: 3 }],
      [{ type: 'knight', count: 4 }],
      [{ type: 'knight', count: 3 }, { type: 'archer', count: 1 }],
      [{ type: 'archer', count: 2 }],
      [{ type: 'archer', count: 3 }],
      [{ type: 'knight', count: 2 }, { type: 'archer', count: 3 }],
      [{ type: 'knight', count: 3 }, { type: 'archer', count: 3 }],
      // Wave 10: BOSS — Iron Champion (STUN WINDOW — hit during stumble only)
      [{ type: 'iron_champion', count: 1 }],
    ],
    npc: {
      name: 'PRINCESSES DOT & VAL',
      col: '#FF88FF',
      portrait: 'princesses',
      introLines: [
        "Oh. Um. You're... here. Hi. I'm Princess Dot. This is Princess Val.",
        "We may have caused a small incident. A VERY small incident. Barely an incident.",
        "We found a book in the restricted library. Old book. Lots of symbols. Very interesting.",
        "We may have read some of the symbols out loud. In sequence. Three times.",
        "That was apparently enough to summon something called the Nexus into the broadcast tower.",
        "We panicked. We sent the castle army to stop you from, uh, finding out about it.",
        "We want to be clear: we deeply regret that decision. In hindsight: not ideal.",
        "Our Iron Champion has already been deployed. He's enormous. He charges through walls.",
        "Wait for him to stumble after a charge. That is your window. Hit him THEN.",
        "Please take him down. And also please don't tell the Queen what we did.",
      ],
      outroLines: [
        "The Champion is down. You are very good at this.",
        "We would like to formally apologise. For the army. And the Nexus. And the book.",
        "The broadcast tower is north-east, in the Tech District. Red light on top. You'll see it.",
        "The Nexus Core is in there. We accidentally summoned it. We are aware that this is bad.",
        "It absorbs single energy inputs and repairs itself. Don't hit it once. Hit it TWICE.",
        "Two simultaneous impacts, or one enormous explosive hit. That's the only way.",
        "We designed it to be unbeatable. We were showing off. We are very sorry.",
        "It's also started calling itself 'enlightened'. That part wasn't in the book.",
        "The Queen found out what we did. We are grounded. Indefinitely. No exceptions.",
        "So please fix this quickly. We are running out of ways to explain ourselves.",
      ],
    },
    synopsis: 'Princesses Dot & Val summoned the Nexus from a weird book and sent the whole castle army to cover it up. Now they\'re grounded and you\'re cleaning up their mess.',
    mapPos: { x: 462, y: 148 },
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'tower',
    title: 'ACT 5',
    zone: 'BROADCAST TOWER',
    enemyCategory: 'TECH',
    bg: { sky: '#050510', mid: '#0a0a1a', ground: '#1a1a2a', accent: '#00FFCC' },
    waves: [
      [{ type: 'glitch',       count: 1 }],
      [{ type: 'glitch',       count: 2 }],
      [{ type: 'glitch',       count: 3 }],
      [{ type: 'glitch',       count: 4 }],
      [{ type: 'glitch',       count: 3 }, { type: 'tendril',      count: 1 }],
      [{ type: 'tendril',      count: 2 }],
      [{ type: 'tendril',      count: 2 }, { type: 'pulse_orb',    count: 2 }],
      [{ type: 'pulse_orb',    count: 3 }, { type: 'glitch',       count: 2 }],
      [{ type: 'overload_bot', count: 1 }],
      [{ type: 'overload_bot', count: 2 }],
      [{ type: 'overload_bot', count: 2 }, { type: 'glitch',       count: 2 }],
      [{ type: 'tendril',      count: 2 }, { type: 'pulse_orb',    count: 2 }],
      [{ type: 'tendril',      count: 3 }, { type: 'pulse_orb',    count: 3 }, { type: 'glitch', count: 2 }],
      // Wave 14: BOSS — Nexus Core (SIMULTANEOUS — 2 hits within 700ms solo / 300ms coop, or exploding ball)
      [{ type: 'nexus_core', count: 1 }],
    ],
    npc: {
      name: 'ALL SURVIVORS',
      col: '#FFD700',
      portrait: 'everyone',
      introLines: [
        "[RADIO] This is Dr. Wendy — all units, the infection rate is dropping near City Ruins!",
        "[RADIO] Professor Biff here. The Tome says 'the tower will broadcast the truth.'",
        "[RADIO] *meow* General Fluffkins. Requesting you DESTROY THAT TOWER CORE. Please.",
        "[RADIO] Dot and Val here. The Nexus Core is in full override mode. Very, very bad.",
        "The tower is right in front of you. The broadcast antenna is live.",
        "Destroy the Nexus Core and the cure signal will transmit automatically.",
        "WARNING: The Nexus Core HEALS from single hits. It needs SIMULTANEOUS impacts.",
        "Two balls at the same time. Or one massive explosive hit. That also works.",
        "Whatever you do — do NOT let it absorb more energy. It gets stronger each time.",
        "The world is counting on you. No pressure. Loads of pressure. Good luck.",
      ],
      outroLines: [
        "THE SIGNAL IS BROADCASTING!",
        "[Radio] Dr. Wendy: This is the most beautiful thing I've ever seen. I'm definitely not crying.",
        "[Radio] Prof. Biff: I'm updating the Tome. New chapter: 'The Heroes Who Threw True.'",
        "[Radio] Gen. Fluffkins: *extended purring* This is acceptable. Well done.",
        "[Radio] Princesses Dot & Val: Our paper has 47 citations already. That's a record.",
        "The WHO has issued an emergency statement: 'Dodgeball is now official medicine.'",
        "General Fluffkins has been awarded the Medal of Feline Honor. Officially denied crying.",
        "Professor Biff is already writing a sequel tome. It's mostly about you.",
        "Dr. Wendy's paper has been downloaded 4 million times. She is not done crying.",
        "THE END  —  Thank you for playing DODGXEL!  Now go play another match. Doctor's orders.",
      ],
    },
    synopsis: 'The Nexus Core AI controls the broadcast tower — and it thinks it\'s a god. Hit it twice, simultaneously. Broadcast the cure. End this.',
    mapPos: { x: 555, y: 72 },
  },
];
